services:
  tpn.email_templates.command.instructions_remover:
    class: TPN\EmailTemplatesComponent\Command\InstructionsRemover
    tags:
      - {name: "email_template_enricher_command", index: 1}

  tpn.email_templates.command.tags_remover:
    class: TPN\EmailTemplatesComponent\Command\NotAllowedTagsRemover
    tags:
      - {name: "email_template_enricher_command", index: 2}

  tpn.email_templates.command.variables_includer:
    class: TPN\EmailTemplatesComponent\Command\VariablesIncluder
    calls:
      - [setTemplateVariables, [%tpn.email_templates.template_variables%]]
    tags:
      - {name: "email_template_enricher_command", index: 3}

  tpn.email_templates.command.template_extender:
    class: TPN\EmailTemplatesComponent\Command\TemplateExtender
    calls:
      - [setHeaderTemplate, [%tpn.client_api_client.header%]]
      - [setFooterTemplate, [%tpn.client_api_client.footer%]]
      - [setStylesTemplate, [%tpn.client_api_client.styles%]]
    tags:
      - {name: "email_template_enricher_command", index: 4}
