services:
    tpn.email_templates.factory.email_template:
        class: TPN\EmailTemplatesComponent\Model\Factory\EmailTemplateFactory
        arguments:
          - @jms_serializer
          - @tpn.email_templates.array_converter
          - @tpn.email_templates.validator
          - @logger

    tpn.email_templates.factory.element:
        class: TPN\EmailTemplatesComponent\Element\ElementFactory
